### ISSUE TITLE
Menu structure

### ISSUE THREAD

**Issue by wtty** [mobizel/markdown-docs-bundle#82]
The current menu structure is automatically generated based off the first `h1` title in a markdown document and sorted alphabetically but I didn't see a way to sort the menu explicitly other than by using titles with numbers or just creating the menu manually.

Is there a way to override the default generated menu structure?

**Comment by loic425** [comment]
Yes, for now the only way to sort menu items and pages (pagination) is to use titles with numbers .
You can use [decoration](https://symfony.com/doc/current/service_container/service_decoration.html) to use your own system to override to use your own PageSorter.
Cause we are not on a stable release and I don't have any BC-promise yet, I suggest you to make a PR if you have an idea to propose an alternative way of sorting the pages.

**Comment by loic425** [comment]
It is now released https://github.com/mobizel/markdown-docs-bundle/releases/tag/v0.10.0

upgrade the bundle: 
```bash
composer require mobizel/markdown-docs-bundle "^0.10"
```

To see how to use custom sorting:
https://github.com/mobizel/markdown-docs-bundle/blob/master/docs/how-to-customize-pages-positions.md

**Comment by loic425** [comment]
@wtty Have you tried the new release to customize positions of your pages?
